# Docker-compose.dev.yml

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: dev-app1
    restart: unless-stopped
    tty: true
    environment:
      SERVICE_NAME: app
      SERVICE_TAGS: dev
    working_dir: /var/www
    env_file:
      - .env
    volumes:
      - .:/var/www
      - ./vendor:/var/www/vendor
      - ./docker-compose/php/local.ini:/usr/local/etc/php/conf.d/local.ini
    networks:
      - app-network
    depends_on:
      - db

  webserver:
    image: nginx:alpine
    container_name: dev-nginx1
    restart: unless-stopped
    ports:
      - "8088:80"
    volumes:
      - .:/var/www
      - ./docker-compose/nginx:/etc/nginx/conf.d/
    networks:
      - app-network

  adminer:
    image: adminer
    container_name: dev-adminer1
    restart: unless-stopped
    ports:
      - "8089:8080"
    networks:
      - app-network

  db:
    image: postgres:15
    container_name: dev-db1
    restart: unless-stopped
    environment:
      POSTGRES_USER: dev_user
      POSTGRES_PASSWORD: dev_password
      POSTGRES_DB: dev_db
    ports:
      - "5439:5432"
    volumes:
      - dbdata:/var/lib/postgresql/data
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  laravel-app-code:
  dbdata:
    driver: local
