# Docker-compose.yml
# Note: This is used to set up a local database/adminer instance

version: "3.8"

services:
    db:
        image: postgres:15
        container_name: dev-postgres2
        restart: unless-stopped
        environment:
            POSTGRES_USER: dev_user
            POSTGRES_PASSWORD: dev_password
            POSTGRES_DB: dev_db
        ports:
            - "5556:5432" # Map PostgreSQL container port 5432 to localhost:5556
        volumes:
            - dev-dbdata:/var/lib/postgresql/data
        networks:
            - app-network

    adminer:
        image: adminer
        container_name: dev-adminer2
        restart: unless-stopped
        ports:
            - "8082:8080" # Expose Adminer at localhost:8080
        networks:
            - app-network

volumes:
    dev-dbdata:
        driver: local

networks:
    app-network:
        driver: bridge
